import { readFile } from "node:fs/promises";
import path from "node:path";

import type { ActivityFeed } from "./activity";

/**
 * Read the feed on the server so its text is in the HTML source.
 *
 * Fetching it only on the client leaves the commit list as "reading…" in the
 * markup — invisible to a crawler, to a preview card, and to anyone with
 * JavaScript off. Since the collector already writes a static file, the server
 * can just read it, and the client refetches afterwards for freshness.
 *
 * Server-only: this imports node:fs, so a client component importing it fails
 * the build rather than shipping a broken bundle.
 */
export async function readActivity(): Promise<ActivityFeed | null> {
  try {
    const file = path.join(process.cwd(), "public", "data", "activity.json");
    return JSON.parse(await readFile(file, "utf8")) as ActivityFeed;
  } catch {
    // The file is generated by a scheduled job, so a fresh clone won't have one
    // yet. The client fetch still runs; this only costs the SSR'd copy.
    return null;
  }
}
