import type { ActivityFeed } from "@/lib/activity";
import type { LeetCodeStats } from "@/lib/leetcode";
import { BOXES, PROFILE } from "@/lib/profile";

import { CommitFeed } from "./screens/CommitFeed";
import { LeetCodePanel } from "./screens/LeetCode";
import { NowPlaying } from "./screens/NowPlaying";

/**
 * The site without the room.
 *
 * Served to phones below the hero, and served alone to anything that can't or
 * shouldn't run the canvas. It is not a degraded version — it carries exactly
 * the same content, and for a recruiter skimming on a train it is the better
 * experience of the two. Building it well is also what lets the 3D be
 * uncompromising, since nobody is stuck with the 3D.
 *
 * Rendered on the server, so the text is in the HTML source and indexable
 * regardless of which mode a visitor ends up in.
 */
export function Flat({
  feed,
  leetcode,
}: {
  feed: ActivityFeed | null;
  /**
   * Passed in from the server rather than fetched on the client, because this
   * component *is* the HTML source — it's what a crawler and a reader with
   * JavaScript off get. The copy of this panel on the 3D centre monitor fetches
   * its own, since threading a second prop through five layers of scene graph
   * to reach a card in a sidebar is a worse trade than one extra request in the
   * mode that is already running a WebGL renderer.
   */
  leetcode: LeetCodeStats | null;
}) {
  return (
    <div className="mx-auto w-full max-w-3xl px-6 py-16 sm:px-8">
      <header>
        <h1 className="text-4xl font-medium tracking-tight text-ink sm:text-5xl">
          {PROFILE.name}
        </h1>
        <p className="mt-4 inline-block rounded-full bg-accent/12 px-3.5 py-1.5 font-mono text-sm text-accent">
          {PROFILE.role} · {PROFILE.location}
        </p>

        <div className="mt-7 space-y-4 text-[17px] leading-relaxed text-ink-dim">
          {PROFILE.bio.map((p) => (
            <p key={p.slice(0, 24)}>{p}</p>
          ))}
        </div>

        <ul className="mt-8 flex flex-wrap gap-x-7 gap-y-3">
          {[
            ...PROFILE.links,
            {
              label: "Email",
              href: `mailto:${PROFILE.email}`,
              handle: PROFILE.email,
            },
          ].map((link) => (
            <li key={link.label}>
              <a
                href={link.href}
                {...(link.href.startsWith("mailto:")
                  ? {}
                  : { target: "_blank", rel: "noreferrer" })}
                className="group inline-flex items-baseline gap-2"
              >
                <span className="font-mono text-[11px] uppercase tracking-[0.18em] text-ink-faint">
                  {link.label}
                </span>
                <span className="text-[15px] text-ink underline decoration-screen-line underline-offset-4 transition-colors group-hover:decoration-accent">
                  {link.handle}
                </span>
              </a>
            </li>
          ))}
        </ul>
      </header>

      {leetcode && (
        <Section title="LeetCode">
          {/*
            Capped, and left-aligned rather than stretched.

            The panel is designed for a sidebar on a 27" monitor; run out to the
            full width of a reading column it becomes a bar chart with 500 px of
            empty track, which reads as a dashboard widget rather than as a
            statement about someone.
          */}
          <LeetCodePanel stats={leetcode} className="max-w-sm" />
        </Section>
      )}

      <Section title="On the shelf">
        <div className="grid gap-5 sm:grid-cols-2">
          {(["catan", "chess"] as const).map((id) => (
            <BoxCard key={id} id={id} />
          ))}
        </div>
      </Section>

      <Section title="Now playing">
        {/*
          Fixed height: the component is a player client built for a
          monitor-shaped surface, and it needs enough room for a header, a track
          list and a transport bar. At the 320px it used to get, all three were
          fighting over the same forty pixels.
        */}
        <div className="overflow-hidden rounded-panel ring-1 ring-screen-line">
          <div className="h-[560px]">
            <NowPlaying />
          </div>
        </div>
      </Section>

      <Section title="Commits">
        <div className="overflow-hidden rounded-panel ring-1 ring-screen-line">
          <div className="h-[560px]">
            <CommitFeed initial={feed} />
          </div>
        </div>
      </Section>

      <footer className="mt-16 border-t border-screen-line pt-6 font-mono text-[12px] text-ink-faint">
        The commit feed is generated by a scheduled job. Work commits show a type
        label only — their messages never leave the job that collects them.
      </footer>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-16">
      <h2 className="mb-5 font-mono text-[12px] uppercase tracking-[0.2em] text-ink-faint">
        {title}
      </h2>
      {children}
    </section>
  );
}

function BoxCard({ id }: { id: "catan" | "chess" }) {
  const box = BOXES[id];
  return (
    <article className="flex h-full flex-col rounded-panel bg-screen-raised p-7">
      <h3 className="font-mono text-lg font-bold tracking-[0.16em] text-ink">
        {box.title}
      </h3>
      <p className="mt-1 text-sm italic text-ink-faint">{box.tagline}</p>
      <p className="mt-4 flex-1 text-[14px] leading-relaxed text-ink-dim">
        {box.blurb[0]}
      </p>
      <ul className="mt-4 space-y-1.5 text-[12.5px] leading-snug text-ink-faint">
        {box.components.slice(0, 4).map((c) => (
          <li key={c.slice(0, 20)} className="flex gap-2">
            <span aria-hidden className="mt-[7px] size-[4px] shrink-0 bg-ink-faint" />
            <span>{c}</span>
          </li>
        ))}
      </ul>
      <div className="mt-5 flex items-center gap-4">
        {box.playHref && (
          <a
            href={box.playHref}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-2 rounded-full bg-accent px-5 py-2.5 font-mono text-[12px] uppercase tracking-wider text-graphite transition-opacity duration-150 hover:opacity-85"
          >
            <span aria-hidden>▶</span> Play
          </a>
        )}
        {box.repoHref && (
          <a
            href={box.repoHref}
            target="_blank"
            rel="noreferrer"
            className="rounded-full border border-screen-line px-5 py-2.5 font-mono text-[12px] uppercase tracking-wider text-ink-faint transition-colors duration-150 hover:border-accent hover:text-ink"
          >
            Source
          </a>
        )}
        {box.status && (
          <span className="font-mono text-[11px] uppercase tracking-wider text-ink-faint">
            {box.status}
          </span>
        )}
      </div>
    </article>
  );
}
